#title: Your awesome title
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Bla bla bla
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
header_pages:
   - index.md
#   - projects.md
   - about.md

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-feed
  - jekyll-seo-tag
